### ISSUE TITLE
New terminolgy for "top"(?) entieites in an Acorn file

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#20]
Acorn files contain entities that take predicates like `ontologies:hasOutput` and `ontologies:hasRequiredInput`. They have been called "processes", and can be instantiated as `ontologies:TURBO_0010178`, among a few other classes.

Those top(?) entities should be reclassified as SPARQL update statement generation specification, `<http://transformunify.org/ontologies/TURBO_0010354>`

We can create more granular subclasses of `TURBO_0010354` if desired. They could include expansion specifications, entity linking specifications, etc. (provided those things can be defined.)

Instances of `TURBO_0010354` specify how a SPARQL update statement should be generated. The generated SPARQL update statement can subsequently be issued against a triplestore as part of a SPARQL update process, `TURBO_0010347`

**Comment by greenguy33** [comment]
Thanks for creating this class. I will replace the current class with this.
