### ISSUE TITLE
regression in orphan recipe checking

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#26]
@greenguy33 you added bi-directional checking on specifications and recipes recent, didn't you? 

There shouldn't be any specification that takes an undefined recipe as "input" or "output"

AND

there shouldn't be any recipes that aren't the "input" or "output" of at least one specification

I think some of those cases are still slipping through.  I'll post examples in an hour or so.

**Comment by greenguy33** [comment]
I agree that there is validation for the first (no undefined recipes as input or output), but I don't believe that I've added anything regarding the second (no recipes that aren't an input or an output)

It might at some time be useful to have recipes which are not input or output if you are sandboxing something up or want to temporarily detach one of the recipes for development purposes.

**Comment by turbomam** [comment]
see #21
