### ISSUE TITLE
Can Drivetrain clear multiple production named graphs?

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#31]
```
09:45:38.962 [run-main-2] INFO  edu.upenn.turbo.DrivetrainDriver$ - Clearing production named graphs...
```
`turbo_properties.properties` has a `productionRepository` property and a `clearGraphsAtStart` but no "graphs to be cleared" property

What graphs are cleared? This may not require any changes, just telling me or reminding me.

**Comment by greenguy33** [comment]
Graphs cleared are the values of `processNamedGraph` and `expandedNamedGraph` in properties file
