### ISSUE TITLE
Two dependents in a ontologies:TurboGraphVariableManipulationLogic?

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#32]
I have a `ontologies:TurboGraphVariableManipulationLogic`  called `ontologies:MeasCodeMentionedClassListFromValueRule`

I want to say that Synthea/OMOP measurement rows, instantiated as measurement datums, mention the URI for a code from some biomedical terminology. 

We did the same kind of thing for procedures. All of the procedures mention a SNOMED code, **but the measurements can mention either a SNOMED code or a LOINC code.**

So I would like to be able to say something like

```
ontologies:MeasCodeMentionedClassListFromValueRule
  a ontologies:TurboGraphVariableManipulationLogic ;
  ontologies:usesSparql """
  BIND(uri(concat('http://purl.bioontology.org/ontology/', ${dependent1}, '/',  ${dependent2} )) as  ${replacement} )
"""  ;
.

ontologies:MeasVocabShortcut 
  a ontologies:DatatypeConnectionRecipe ;
  ontologies:multiplicity ontologies:1-1 ;
  ontologies:object ontologies:measurement_vocabulary_id_StringLiteralValue ;
  ontologies:objectRequiredToCreate1 ontologies:MeasCodeMentionedClassList ;
  ontologies:predicate <http://api.stardog.com/measurement#vocabulary_id> ;
  ontologies:subject <http://api.stardog.com/measurement> ;
.

ontologies:MeasCodeShortcut 
  a ontologies:DatatypeConnectionRecipe ;
  ontologies:multiplicity ontologies:1-1 ;
  ontologies:object ontologies:measurement_source_value_StringLiteralValue ;
  ontologies:objectRequiredToCreate2 ontologies:MeasCodeMentionedClassList ;
  ontologies:predicate <http://api.stardog.com/measurement#measurement_source_value> ;
  ontologies:subject <http://api.stardog.com/measurement> ;
.
```

**Comment by greenguy33** [comment]
Hey @turbomam, I'm doing something similar with a diagnosis mentioning either a Snomed term or an ICD term. Here's the relevant bits from the legacy Acorn files. They key difference between your approach and mine is that I am defining two separate custom rules, `IcdDiagnosisRegistryRule` and `SnomedDiagnosisRegistryRule` .

```
pmbb:DiagnosisExpansionProcess
  a turbo:TURBO_0010354 ;
  ontologies:hasOptionalInput ontologies:shortcutDiagnosisToDiagnosisCode ;
  ontologies:hasOutput ontologies:diagnosisToIcdTerm ;
  ontologies:hasOutput ontologies:diagnosisToSnomedTerm ;
.
ontologies:shortcutDiagnosisToDiagnosisCode
  a ontologies:DatatypeConnectionRecipe ;
  ontologies:multiplicity <http://transformunify.org/ontologies/1-1> ;
  ontologies:object ontologies:diagnosisTermSuffixStringLiteralValue ;
  ontologies:predicate ontologies:TURBO_0004601 ;
  ontologies:subject ontologies:TURBO_0010160 ;
.
ontologies:diagnosisToIcdTerm
  a ontologies:ObjectConnectionToTermRecipe ;
  ontologies:multiplicity <http://transformunify.org/ontologies/1-1> ;
  ontologies:object ontologies:IcdTermOfVariousTypes ;
  ontologies:predicate obo:IAO_0000142 ;
  ontologies:subject obo:OGMS_0000073 ;
.
ontologies:diagnosisToSnomedTerm
  a ontologies:ObjectConnectionToTermRecipe ;
  ontologies:multiplicity <http://transformunify.org/ontologies/1-1> ;
  ontologies:object ontologies:SnomedTermOfVariousTypes ;
  ontologies:predicate obo:IAO_0000142 ;
  ontologies:required ontologies:notRequired ;
  ontologies:subject obo:OGMS_0000073 ;
.
ontologies:IcdTermOfVariousTypes 
  a ontologies:MultiObjectDescriber ;
  ontologies:usesCustomVariableManipulationRule ontologies:IcdDiagnosisRegistryRule ;
.
ontologies:SnomedTermOfVariousTypes 
  a ontologies:MultiObjectDescriber ;
  ontologies:usesCustomVariableManipulationRule ontologies:SnomedDiagnosisRegistryRule ;
.
'''

**Comment by greenguy33** [comment]
It also looks at first glance as if the objects of both of the connection recipes which you posted may be composed of the same variable ```ontologies:measurement_vocabulary_id_StringLiteralValue``` You may want to define two different variables for this.

**Comment by greenguy33** [comment]
At second glance, it looks like you are trying to construct a URI with the prefix ```http://purl.bioontology.org/ontology/``` followed by the value of ```ontologies:measurement_vocabulary_id_StringLiteralValue``` followed by a slash, followed by the value of ```ontologies:measurement_source_value_StringLiteralValue```.  Is that really what you are trying to do? If so, it seems like a different case to me than what you described as *the measurements can mention either a SNOMED code or a LOINC code*, which implied to me the value of one or the other would be used in creation of the URI, but not both at the same time.

**Comment by turbomam** [comment]
Yes, I would like to construct URIs like

`http://purl.bioontology.org/ontology/LOINC/ 29463-7`

or

`http://purl.bioontology.org/ontology/SNOMED/ 428191000124101`

`LOINC` or `SNOMED` will come from from `ontologies:measurement_vocabulary_id_StringLiteralValue`

The final part of the URI will come from `ontologies:measurement_source_value_StringLiteralValue`

The SNOMED URIs may be less important if @cstoeckert  decides he doesn't want to bucket and instantiate all Synthea/OMOP measurements rows. I think all of the measurements I have mapped so far have all been LOINC terms.

**Comment by greenguy33** [comment]
The quickest way to get this done with the current code base would be to hard code one of the variables into the custom rule. It's not the cleanest solution but should get the job done.
```
ontologies:MeasCodeMentionedClassListFromValueRule
  a ontologies:TurboGraphVariableManipulationLogic ;
  ontologies:usesSparql """
  BIND(uri(concat('http://purl.bioontology.org/ontology/', ${dependent}, '/',  ?measurement_source_value_StringLiteralValue )) as  ${replacement} )
"""  ;
.

**Comment by turbomam** [comment]
ok i'll try that
