### ISSUE TITLE
misleading "no input named graphs found" INFO

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#5]
If an Acorn input recipe includes a triple pattern that isn't in the input graph, the following `INFO` is printed:

> Cannot run process http://transformunify.org/ontologies/post_icbo_synthea_omop_cnp_procedures: no input named graphs found

Even if the input named graph is present.

@greenguy33  could you please change that to something like 

>  Cannot run process http://transformunify.org/ontologies/post_icbo_synthea_omop_cnp_procedures: specified pattern is not found in specified named graph?

**Comment by greenguy33** [comment]
This type of error message will likely not exist anymore after input data validator is up and running

**Comment by turbomam** [comment]
@greenguy33 you can close this when you think the relevant input data validator is up and running.

I'll reopen if I think I see an unwarranted message like this again:

>Cannot run process http://transformunify.org/ontologies/post_icbo_synthea_omop_cnp_procedures: no input named graphs found
