### ISSUE TITLE
We shouldn't be using pmbb: IRIs for non-PMBB data

### ISSUE THREAD

**Issue by turbomam** [PennTURBO/Drivetrain#6]
It looks like Acorn uses the IRI base `http://www.itmat.upenn.edu/biobank/` and the prefix `pmbb:` in the construction of all all new instance IRIs.

That's doesn't make sense for instantiating data from Synthea/OMOP or even non-PMBB data from PDS.

New instances created by Acorn should use a generic IRI base and prefix, or the IRI base and prefix should be user-specified parameters.

**Comment by turbomam** [comment]
maybe `http://upibi.org/` or `https://github.com/PennTURBO/Drivetrain/`

**Comment by greenguy33** [comment]
Use property "defaultPrefix" in properties file to define custom prefix. This is now a required property.

**Comment by turbomam** [comment]
Thanks @greenguy33 , will try `defaultPrefix` now.
